require 'flanks/version'
require 'flanks/configuration'
require 'flanks/base'
require 'flanks/error'
require 'flanks/resource'
require 'flanks/collection'

require 'flanks/resources/account'
require 'flanks/resources/bank'
require 'flanks/resources/link'
require 'flanks/resources/link_code'
require 'flanks/resources/token'
require 'flanks/resources/transaction'
